removing local.sql as no longer required, amending readme
alphagov/notifications-functional-tests pull request #522
Opened 2024-09-17 15:47 UTC by emmetdev

2024-09-18 09:50 UTC, robinjam requested changes
Could you also update the "Database fixtures" section further down in the readme?

2024-09-18 09:51 UTC, robinjam commented on README.md
> +Make generate-local-dev-db-fixtures
Also `make` needs to be lowercase

2024-09-18 14:28 UTC, emmetdev commented on README.md
> +Make generate-local-dev-db-fixtures
Switched to lower case

2024-09-18 16:29 UTC, robinjam approved these changes
LGTM, nice!

Couple of non-blocking suggestions, feel free to merge them or discard them.

2024-09-18 16:29 UTC, robinjam commented on README.md
> +For your local environment, these fixtures are now generated using the custom flask command functional-test-fixtures in notifications-api/app/command.py. The command will create all the database rows
```suggestion
For your local environment, these fixtures are now generated using the custom flask command functional-test-fixtures (defined in [notifications-api/app/functional_tests_fixtures/__init__.py](https://github.com/alphagov/notifications-api/blob/main/app/functional_tests_fixtures/__init__.py)). The command will create all the database rows required for the funcitonal tests in an idempotent way and output an environment file the functional tests can use to execute against the environment. There are [instructions on how to update the local database fixtures](docs/update-local-db-fixtures.md).
```

2024-09-18 16:29 UTC, robinjam commented on docs/update-local-db-fixtures.md
> +4. Update the function apply_fixtures() in notifications-api/app/functional_tests_fixtures/__init__.py to make changes to the fixtures. Fixtures should be added using the API in an idempotent way.
```suggestion
4. Update the function apply_fixtures() in [notifications-api/app/functional_tests_fixtures/__init__.py](https://github.com/alphagov/notifications-api/blob/main/app/functional_tests_fixtures/__init__.py) to make changes to the fixtures. Fixtures should be added using the API in an idempotent way.
```

2024-09-23 16:22 UTC, robinjam approved these changes

2024-09-23 16:33 UTC, merged