Fix functional tests
alphagov/notifications-functional-tests pull request #549
Opened 2024-12-31 14:56 UTC by spatel033

There are multiple tests are failing when deploying admin. Additionally failing flaky tests cases in preview and also in dev environment. This PRs covers fixing multiple test cases and tested in dev-c environment. More details on [this card](https://trello.com/c/w9hwX6yF/1086-fix-functional-tests).

2025-01-02 13:59 UTC, joybytes approved these changes

2025-01-02 16:24 UTC, CrystalPea approved these changes

2025-01-02 17:17 UTC, leohemsted requested changes

2025-01-02 17:17 UTC, leohemsted commented on tests/test_utils.py
> +    SENT = RECEIVED | DELIVERED | {"sending", "pending", "created"}
why is the status still in `created`? is it stuck in our system? if so, we need to wait for it to progress

can you give an example of a notification ID on preview that was stuck in created? how long was it stuck for? was it from a job, or from api? etc?

i don't buy "sometimes things for mmg are stuck in created" - as soon as we send to MMG, we must update immediately to `sending` or notify is severely broken

2025-01-02 17:17 UTC, leohemsted commented on tests/pages/pages.py
> +        self.driver.execute_script("window.scrollTo(0, 50)")
cc @tombye i think this is the one here:
![image](https://github.com/user-attachments/assets/767f412b-e23f-4e06-9b3b-33ec57b7a955)

dont know if we have a bug for this in trello?

2025-01-02 17:17 UTC, leohemsted commented on tests/functional/preview_and_dev/test_unsubscribe_requests.py
> +    time.sleep(10)
i don't love random sleeps - what's happening here?

Do you have a link to a concourse job that failed at this point or a screenshot or something? cant figure out how `report_page.click_download_report_link()` would result in a different result without this sleep.

the click function should wait up to ten seconds anyway - if these unsubscribe reports take more than twenty seconds to load, that's an issue in of itself

2025-01-02 17:17 UTC, leohemsted commented on tests/functional/preview_and_dev/test_registration_and_invite.py
> +    do_user_add_new_service(driver)
this means that we won't have user registration or create the service if we just run `test_can_add_and_update_reply_to` or `test_can_add_and_update_sms_sender_of_service` 🤔 

is that ok? is this necessary?

2025-01-03 11:15 UTC, klssmith commented on tests/test_utils.py
> +    SENT = RECEIVED | DELIVERED | {"sending", "pending", "created"}
I think MMG messages are staying in `created` because we're getting an error when sending to them on dev environments due to having run out of credit. It looks like we only update to `sending` if there were no exceptions raised when sending. We are just looking at increasing the credit though, which should mean we don't need to add "created" here (see https://gds.slack.com/archives/C03QVEHD4EA/p1734616273586009 for details)

2025-01-03 12:54 UTC, leohemsted commented on tests/test_utils.py
> +    SENT = RECEIVED | DELIVERED | {"sending", "pending", "created"}
ahhh thanks for the context. yes i'd rather we fix the issues with credit - we rely on these enums for everything incl smoke tests. if we can't send by MMG, that's a test failure.

2025-01-03 18:09 UTC, spatel033 commented on tests/pages/pages.py
> +        self.driver.execute_script("window.scrollTo(0, 50)")
I think it was part of [this card](https://trello.com/c/wPRphm25/998-the-sticky-footer-sometimes-overlaps-focused-elements?search_id=5cadd11e-418e-49f2-9f71-008499f6c48a). Dropped the changes for now.

2025-01-03 18:10 UTC, spatel033 commented on tests/functional/preview_and_dev/test_registration_and_invite.py
> +    do_user_add_new_service(driver)
Good point!! Refactored the fixture for the function scope

2025-01-03 18:13 UTC, spatel033 commented on tests/functional/preview_and_dev/test_unsubscribe_requests.py
> +    time.sleep(10)
Few times replicated in dev environment, will need to investigate further. For now removing this change.

2025-01-03 18:17 UTC, spatel033 commented on tests/test_utils.py
> +    SENT = RECEIVED | DELIVERED | {"sending", "pending", "created"}
Thanks @klssmith. Since this is Dev only issue, will create ticket for this to fix the issue for credit related status update.

2025-01-06 15:29 UTC, leohemsted commented on tests/functional/preview_and_dev/test_join_live_service.py
> +        _do_requester_sign_in(driver)
im wondering what happens if a timeout happens during `do_user_registration` - i dont think we should be trying to sign in in that case - just checking the sign_in_page should be enough I think? So I think this is a bit safer:

```python
    try:
        sign_in_page.wait_until_current()
    except TimeoutException:
        # if we didn't get to the sign_in_page, it's probably because we're already logged in.
        # try logging out before proceeding
        _do_requester_sign_in(driver)
    else:
        do_user_registration(driver)
```

2025-01-06 15:29 UTC, leohemsted commented on tests/functional/preview_and_dev/test_registration_and_invite.py
> +        _sign_in_again(driver)
same comment as above - i think we can use `else` here to only run registration/service creation if the user isn't signed up and it doesnt raise an exception

```python
    try:
        sign_in_page.wait_until_current()
    except TimeoutException:
        # if we didn't get to the sign_in_page, it's probably because we're already logged in.
        # try logging out before proceeding
        _sign_in_again(driver)
    else:
        do_user_registration(driver)
        do_user_add_new_service(driver)
```

2025-01-06 23:41 UTC, leohemsted approved these changes

2025-01-07 11:04 UTC, merged